name: Update JSON File

on:
  schedule:
    - cron: '*/5 * * * *'
  # workflow_dispatch:  # 手動実行用

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install nokogiri
          gem install json

      - name: Run Ruby script
        run: ruby crawler.rb

      - name: Commit and push if changed
        run: |
          git config --global user.name 'itaya_yuichiro'
          git config --global user.email 'mr.itaya.magic@gmail.com'
          git add site_info.json
          git commit -m "generated" --allow-empty
          git diff-index --quiet HEAD || git push
